//go:build ignore

package main

import (
	"flag"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"text/template"
)

const (
	ignoreFilePrefix1 = "gen-"
	ignoreFilePrefix2 = "github-"
	outputFileSuffix  = "-stringify_test.go"
)

var (
	check   = flag.Bool("check", false, "Check whether generated files are up to date")
	verbose = flag.Bool("v", false, "Print verbose log messages")

	skipStructMethods = map[string]bool{}

	skipStructs = map[string]bool{
		"RateLimits": true,
	}

	funcMap = template.FuncMap{
		"isNotLast": func(index int, slice []*structField) string {
			if index+1 < len(slice) {
				return ", "
			}
			return ""
		},
		"processZeroValue": func(v string) string {
			switch v {
			case "false":
				return "false"
			case "Ptr(false)":
				return "false"
			case "Ptr(0.0)":
				return "0"
			case "0", "Ptr(0)", "Ptr(int64(0))":
				return "0"
			case `""`, `Ptr("")`:
				return `""`
			case "Timestamp{}", "&Timestamp{}":
				return "github.Timestamp{0001-01-01 00:00:00 +0000 UTC}"
			case "nil":
				return "map[]"
			case `[]int{0}`:
				return `[0]`
			case `[]string{""}`:
				return `[""]`
			case "[]Scope{ScopeNone}":
				return `["(no scope)"]`
			case "[]any{nil}":
				return "[<nil>]"
			}
			log.Fatalf("Unhandled zero value: %q", v)
			return ""
		},
	}

	sourceTmpl = template.Must(template.New("source").Funcs(funcMap).Parse(source))
)

func isCheck() bool { _ = "STUB: not implemented"; return false }

func main() {
	flag.Parse()
	fset := token.NewFileSet()

	pkgs, err := parser.ParseDir(fset, ".", sourceFilter, 0)
	if err != nil {
		log.Fatal(err)
		return
	}

	for pkgName, pkg := range pkgs {
		t := &templateData{
			filename:     pkgName + outputFileSuffix,
			Year:         2019,
			Package:      pkgName,
			Imports:      map[string]string{"testing": "testing"},
			StringFuncs:  map[string]bool{},
			StructFields: map[string][]*structField{},
		}
		for filename, f := range pkg.Files {
			logf("Processing %v...", filename)
			if err := t.processAST(f); err != nil {
				log.Fatal(err)
			}
		}
		if err := t.dump(); err != nil {
			log.Fatal(err)
		}
	}
	logf("Done.")
}

func sourceFilter(fi os.FileInfo) bool { _ = "STUB: not implemented"; return false }

type templateData struct {
	filename     string
	Year         int
	Package      string
	Imports      map[string]string
	StringFuncs  map[string]bool
	StructFields map[string][]*structField
}

type structField struct {
	sortVal      string
	ReceiverVar  string
	ReceiverType string
	FieldName    string
	FieldType    string
	ZeroValue    string
	NamedStruct  bool
}

func (t *templateData) processAST(f *ast.File) error { _ = "STUB: not implemented"; return nil }

func (t *templateData) addMapType(receiverType, fieldName string) {
	_ = "STUB: not implemented"
	return
}

func (t *templateData) addIdent(x *ast.Ident, receiverType, fieldName string) {
	_ = "STUB: not implemented"
	return
}

func (t *templateData) addIdentPtr(x *ast.Ident, receiverType, fieldName string) {
	_ = "STUB: not implemented"
	return
}

func (t *templateData) addIdentSlice(x *ast.Ident, receiverType, fieldName string) {
	_ = "STUB: not implemented"
	return
}

func (t *templateData) dump() error { _ = "STUB: not implemented"; return nil }

func newStructField(receiverType, fieldName, fieldType, zeroValue string, namedStruct bool) *structField {
	_ = "STUB: not implemented"
	return nil
}

func logf(fmt string, args ...any) { _ = "STUB: not implemented"; return }

const source = `// Code generated by gen-stringify-tests; DO NOT EDIT.
// Instead, please run "go generate ./..." as described here:
// https://github.com/google/go-github/blob/master/CONTRIBUTING.md#submitting-a-patch

// Copyright {{.Year}} The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package {{ $package := .Package}}{{$package}}
{{with .Imports}}
import (
  {{- range . -}}
  "{{.}}"
  {{end -}}
)
{{end}}
{{range $key, $value := .StructFields}}
func Test{{ $key }}_String(t *testing.T) {
  t.Parallel()
  v := {{ $key }}{ {{range .}}{{if .NamedStruct}}
    {{ .FieldName }}: &{{ .FieldType }}{},{{else}}
    {{ .FieldName }}: {{.ZeroValue}},{{end}}{{end}}
  }
 	want := ` + "`" + `{{ $package }}.{{ $key }}{{ $slice := . }}{
{{- range $ind, $val := .}}{{if .NamedStruct}}{{ .FieldName }}:{{ $package }}.{{ .FieldType }}{}{{else}}{{ .FieldName }}:{{ processZeroValue .ZeroValue }}{{end}}{{ isNotLast $ind $slice }}{{end}}}` + "`" + `
	if got := v.String(); got != want {
		t.Errorf("{{ $key }}.String = %v, want %v", got, want)
	}
}
{{end}}
`
